### ISSUE TITLE
Invalid MEF cache => could not load type

### ISSUE THREAD

**Issue by johnholliday** [madskristensen/InsertGuid#1]
<entry>
    <record>4547</record>
    <time>2021/06/07 00:50:39.392</time>
    <type>Error</type>
    <source>Microsoft.VisualStudio.ComponentModelHost.VsShellComponentModelHost</source>
    <description>An invalid MEF cache has been found due to a mismatching timestamp or MVID: Microsoft.VisualStudio.ExtensibilityHosting.InvalidMEFCacheException: The Visual Studio component cache is out of date (assembly: InsertGuid, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null). Please restart Visual Studio.;VS.Platform.ExtensibilityHosting.MefCacheInvalidation.LoadedAssembly.Name=InsertGuid, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null;VS.Platform.ExtensibilityHosting.MefCacheInvalidation.LoadedAssembly.CodeBase=file:///c:/users/john/appdata/local/microsoft/visualstudio/16.0_ba1a16a5/extensions/ctdat30z.pzx/InsertGuid.dll;VS.Platform.ExtensibilityHosting.MefCacheInvalidation.ActualTimestamp=637584529249026387;VS.Platform.ExtensibilityHosting.MefCacheInvalidation.ExpectedTimestamp=636914458776541083;VS.Platform.ExtensibilityHosting.MefCacheInvalidation.ActualMVID=22618d7f-f473-4e8e-a909-e3f32ebd91eb;VS.Platform.ExtensibilityHosting.MefCacheInvalidation.ExpectedMVID=5c163a80-2893-4d6e-b9f0-25098226fb71&#x000D;&#x000A;</description>
  </entry>
  <entry>
    <record>4548</record>
    <time>2021/06/07 00:50:39.394</time>
    <type>Error</type>
    <source>Microsoft.VisualStudio.ComponentModelHost.VsShellComponentModelHost</source>
    <description>A MEF Component threw an exception at runtime: System.TypeLoadException: Could not load type &apos;InsertGuid.Commands.InsertGuidCommand&apos; from assembly &apos;InsertGuid, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null&apos;.&#x000D;&#x000A;   at System.Reflection.RuntimeModule.GetType(RuntimeModule module, String className, Boolean ignoreCase, Boolean throwOnError, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.Reflection.RuntimeModule.GetType(String className, Boolean throwOnError, Boolean ignoreCase)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.Reflection.TypeRef.get_ResolvedType()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.Reflection.ResolverExtensions.Resolve(MethodRef methodRef)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.Reflection.MethodRef.Resolve()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.Reflection.MemberRef.get_MemberInfo()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.&lt;&gt;c__DisplayClass15_0.&lt;GetExportedValueHelper&gt;b__0()</description>
  </entry>
  <entry>
    <record>4549</record>
    <time>2021/06/07 00:50:39.624</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.TypeLoadException: Could not load type &apos;InsertGuid.Commands.InsertGuidCommand&apos; from assembly &apos;InsertGuid, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null&apos;.&#x000D;&#x000A;   at System.Reflection.RuntimeModule.GetType(RuntimeModule module, String className, Boolean ignoreCase, Boolean throwOnError, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.Reflection.RuntimeModule.GetType(String className, Boolean throwOnError, Boolean ignoreCase)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.Reflection.TypeRef.get_ResolvedType()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.Reflection.ResolverExtensions.Resolve(MethodRef methodRef)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.Reflection.MethodRef.Resolve()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.Reflection.MemberRef.get_MemberInfo()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.&lt;&gt;c__DisplayClass15_0.&lt;GetExportedValueHelper&gt;b__0()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.&lt;&gt;c__DisplayClass15_0.&lt;GetExportedValueHelper&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.DelegateServices.&lt;&gt;c__DisplayClass2_0`1.&lt;As&gt;b__0()&#x000D;&#x000A;   at System.Lazy`1.CreateValue()&#x000D;&#x000A;   at System.Lazy`1.LazyInitValue()&#x000D;&#x000A;   at System.Lazy`1.get_Value()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension](Object errorSource, Lazy`1 provider)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>

**Comment by madskristensen** [comment]
That's an issue with VS that should be resolvable by restarting VS
