### ISSUE TITLE
Command not available in F# project

### ISSUE THREAD

**Issue by sdehm** [madskristensen/InsertGuid#2]
When I try to use the key combination to generate a new Guid while in a F# project I get the message _The key combination (Ctrl+K, Ctrl+Space) is bound to command (Insert Guid) which is not currently available._ Is this extension not supported in F# projects?

Thank you!

**Comment by uceumern** [comment]
The same goes for Wix Toolset projects (*.wixproj). Which is a shame, because this is where I have to enter new GUIDs constantly.

**Comment by CZEMacLeod** [comment]
I'm getting the same issue in a .csproj file.
